application:
  version: 1.0.0.1 (v1.0.0.1)


#server:
#  port: 8090


jasypt:
  encryptor:
    # 盐加密
    password: 123456!@#
    # 指定加密方式
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
info:
  username: ENC(Mru5gwjAluKSCxkLxdGIKw==)
  password: ENC(A1+yAABwLTuA5ynz7zUKLQ==)

food:
  meat: 烤肉
  rice: 拌饭
  sauce:
    - 咖喱
    - 蜜汁
    - 原味
#流式语法
#food: {meat: 烤肉,rice: 拌饭}
spring:
  profiles:
    active: dev


---
#开发环境
spring:
  config:
    activate:
      on-profile: dev
server:
  port: 9091


---
#生产环境
spring:
  config:
    activate:
      on-profile: prod
server:
  port: 9092


