server:
  port: 8090
spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/javatest
    username: root
    password: root

  jpa:

    #自动创建|更新|验证数据库表结构
    hibernate:

      ddl-auto: update
    #设置数据库引擎为InnoDB
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    #打印sql语句，方便调试
    show-sql: true
